env:
  browser: true
  es2022: true
  node: true
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - standard-with-typescript
  - prettier
overrides: []
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project:
    - './api/tsconfig.json'
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent: 0
  curly:
    - 2
    - all
  lines-around-comment: 0
  max-len: 0
  no-confusing-arrow: 0
  no-mixed-operators: 2
  no-tabs:
    - 2
    - allowIndentationTabs: true
  no-unexpected-multiline: 2
  quotes:
    - 2
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  no-restricted-syntax: 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/restrict-template-expressions':
    - 2
    - allowNullish: true
ignorePatterns: ['node_modules/', '**/build']
