name: Code Reviewer & Testing
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit linter
        uses: webiny/action-conventional-commits@v1.1.0
  format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 'lts/gallium'
      - name: Install dependencies
        run: npm ci
      - name: Perf format
        run: npm run format:ci
  lint:
    needs: [commit, format]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 'lts/gallium'
      - name: Install dependencies
        run: npm ci
      - name: Lint Perse
        run: npm run lint:ci
